name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
<<<<<<< HEAD
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install system dependencies
        uses: $/.github/workflows/install-deps
        with:
          profile: base
      - name: Install Rust
        uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # v1
        with:
          toolchain: stable
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
=======
        uses: actions/checkout@v6

      - name: Install ubuntu dependencies
        uses: ./.github/workflows/install-deps
        with:
          profile: base

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

>>>>>>> 22e30b0 (chore: added profile)
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@26e9283f268b880168bdbd2c545dfcd60ec2c6ab # v2.87.13
        with:
          tool: cargo-llvm-cov@0.9.0
      - name: Generate code coverage
        run: |
          cargo llvm-cov \
            --workspace \
            --lcov \
            --output-path lcov.info \
            --ignore-filename-regex '(^|/)(src/utils/.*|src/visualization/.*|src/lib\.rs|src/engine/fields/kdtree_mpi\.rs|src/explore/bayesian\.rs)$'
      - name: Upload coverage to Codecov
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
