name:                           coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    name:                       coverage
    runs-on:                    ubuntu-latest
    container:
      image:                    xd009642/tarpaulin:develop-nightly
      options:                  --security-opt seccomp=unconfined
    steps:
      - name:                   Checkout repository
        uses:                   actions/checkout@v3

      - name:                   Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --workspace --timeout 120 --out Xml --exclude-files src/utils/* src/visualization/* src/lib.rs src/engine/fields/kdtree_mpi.rs src/explore/bayesian.rs

      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v3
        with:
          token:                ${{secrets.CODECOV_TOKEN}} # not required for public repos
          files: ./cobertura.xml 
          fail_ci_if_error:     true