name: Rust CI
'on':
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:
  stdbuild:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          - stable
    name: '${{ matrix.os }} ${{ matrix.rust }} build'
    steps:
      - uses: actions/checkout@v6
      - name: Install system dependencies
        if: matrix.os == 'ubuntu-latest'
        uses: ./.github/workflows/install-deps
        with:
          profile: visualization
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '${{ matrix.rust }}'
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: BuildVisualization
        run: 'cargo build --release --features "visualization, visualization_wasm"'
      - name: BuildBayesian
        run: cargo build --release --features bayesian
      - name: Test
        run: cargo test --features parallel
      - name: TestNoFeatures
        run: cargo test
  mpibuild:
    runs-on: '${{ matrix.os }}'
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rust: stable
            mpi: mpich
          - os: macos-15-intel
            rust: stable
            mpi: openmpi
          - os: windows-2022
            rust: stable
            mpi: msmpi
    name: '${{ matrix.os }} MPI'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: '${{ matrix.mpi }}'
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '${{ matrix.rust }}'
      - name: Install system dependencies
        if: matrix.os == 'ubuntu-latest'
        uses: ./.github/workflows/install-deps
        with:
          profile: mpi
      - name: Install macOS dependencies
        if: matrix.os == 'macos-15-intel'
        run: |
          brew install libffi pkg-config
          echo "PKG_CONFIG_PATH=$(brew --prefix libffi)/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "LIBFFI_DIR=$(brew --prefix libffi)" >> $GITHUB_ENV

      - name: Build with MPI
        run: cargo build --release --features distributed_mpi
  nightlybuild:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: 'ubuntu nightly build'
    steps:
      - uses: actions/checkout@v6
      - name: Install system dependencies
        uses: ./.github/workflows/install-deps
        with:
          profile: visualization
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
      - name: Build nightly
        run: cargo build --release
      - name: BuildVisualization nightly
        run: 'cargo build --release --features "visualization, visualization_wasm"'
